image: gitpod/workspace-full:2023-02-27-14-39-56
tasks:
  - name: scenario-setup
    before: |
      printf 'export PATH="$HOME%s:$PATH"\n' "/.astra/cli" | tee -a $HOME/.bashrc
      printf 'unset JAVA_TOOL_OPTIONS\n' | tee -a $HOME/.bashrc
      curl -Ls "https://dtsx.io/get-astra-cli" | sed 's/ASTRA_CLI_VERSION=\"0.6\"/ASTRA_CLI_VERSION=\"0.5\"/' | bash | tee -a ./katapod_logs/astra-cli-install.log
      # adding to path just before .bashrc invokes /home/gitpod/.bashrc.d/60-python to avoid "pyenv: command not found" issues when sshing to host itself
      # The following adds to PATH. Check the "scenario_scripts/prepare_for_ssh.sh" for the other half of the workaround
      sed -i '/\$HOME\/.bashrc.d\//i export PATH=\"\/home\/gitpod\/.pyenv\/plugins\/pyenv-virtualenv\/shims:/home\/gitpod\/.pyenv\/shims:\/home\/gitpod\/.pyenv\/bin:\$\{PATH\}\"\n' /home/gitpod/.bashrc
    init: |
      docker pull cassandra:4.0
      pip install -r client_application/requirements.txt
      ./scenario_scripts/configure-ssh.sh  | tee -a ./katapod_logs/ssh-setup.log
    command: |
      docker run \
        --name cassandra-origin-1 \
        -v ${PWD}/origin_config/cassandra-4.0.yaml:/etc/cassandra/cassandra.yaml \
        -d \
        cassandra:4.0
      sleep 10
      docker exec cassandra-origin-1 bash -c "
        apt-get update && apt-get install -y \
          python-is-python3 \
          unzip \
          python3-venv \
          jq \
          apt-transport-https \
          ca-certificates \
          gnupg \
          curl \
          sudo && \
        curl \"https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip\" -o \"awscliv2.zip\" && \
        unzip awscliv2.zip && ./aws/install && rm -rf awscliv2.zip aws && \
        apt-get clean && rm -rf /var/lib/apt/lists/*
      "
      source /home/gitpod/.astra/cli/astra-init.sh
ports:
  - port: 22
    onOpen: ignore
  - port: 3000
    onOpen: ignore
  - port: 8000
    onOpen: ignore
  - port: 9100
    onOpen: ignore
  - port: 9042
    onOpen: ignore
  - port: 9090
    onOpen: ignore
github:
  prebuilds:
    main: true
vscode:
   extensions:
    - https://github.com/DataStax-Academy/katapod/releases/download/stable/katapod-stable.vsix
