--- insert sample rows into origin

USE zdmapp;

INSERT INTO user_status (user, when, status) VALUES ('eva', '2025-01-22 12:00:00', 'Online');
INSERT INTO user_status (user, when, status) VALUES ('eva', '2025-01-22 13:00:00', 'Away');
INSERT INTO user_status (user, when, status) VALUES ('eva', '2025-01-22 14:00:00', 'Asleep');
INSERT INTO user_status (user, when, status) VALUES ('marco', '2025-01-22 13:30:00', 'Awake');

